file = "household_power_consumption.txt"
#reading select rows by read.table(only works for this database where seleted data is continuous)
DF.row1 <- read.table(file, header = TRUE,sep=";", nrow = 1)
nc <- ncol(DF.row1)
DF.Date <- read.table(file, header = TRUE,sep = ";", as.is = TRUE, 
                      colClasses = c(NA, rep("NULL", nc - 1)))
n12 <- which(DF.Date$Date == "1/2/2007")
n22 <- which(DF.Date$Date == "2/2/2007")
epc <- read.table(file, sep=";", col.names = names(DF.row1), nrows= length(n12)+length(n22),
                  skip = n12[1], as.is = TRUE)

library(lubridate)
epc$Date_Time <- dmy_hms(paste(epc$Date,epc$Time))
png(file = "plot4.png",width = 480, height = 480, units = "px")  
par(mfrow = c(2,2))
plot(epc$Date_Time,epc$Global_active_power,type="n",xlab="",ylab="GLobal Active Power")
lines(epc$Date_Time,epc$Global_active_power)
plot(epc$Date_Time,epc$Voltage,type="n",xlab="datetime",ylab="Voltage")
lines(epc$Date_Time,epc$Voltage)
plot(epc$Date_Time,epc$Sub_metering_1,type="n",xlab="",ylab="Energy sub metering")
lines(epc$Date_Time,epc$Sub_metering_1,col="black")
lines(epc$Date_Time,epc$Sub_metering_2,col="red")
lines(epc$Date_Time,epc$Sub_metering_3,col="blue")
legend("topright",lty = 1,col = c("black","red","blue"),bty="n",legend =c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
plot(epc$Date_Time,epc$Global_reactive_power,type="n",xlab="datetime",ylab="Global_reactive_power")
lines(epc$Date_Time,epc$Global_reactive_power)
dev.off()